version: '3'
services:
  users:
    build:
      context: ./
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vm.cloud.cbh.kth.se:2757/patientjournal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: wiljamniklas