apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-users
  template:
    metadata:
      labels:
        app: fullstack-users
    spec:
      containers:
        - name: fullstack-users
          image: registry.cloud.cbh.kth.se/deploy-dac1887e-42b2-4716-abe1-fd266d22921d/users-wwnr

