#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: fullstack-users
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: fullstack-users
#  template:
#    metadata:
#      labels:
#        app: fullstack-users
#    spec:
#      containers:
#        - name: fullstack-users
#          image: wiljam/services