apiVersion: v1
kind: Service
metadata:
  name: fullstack-users
spec:
  selector:
    app: fullstack-users
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081  # range 30000-32767

  type: NodePort
