spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://vm.cloud.cbh.kth.se:2788/patientjournal
    username: root
    password: wiljamniklas

logging:
  file:
    name: fullstack-users.log
    path: /var/log
  level:
    org.springframework: DEBUG
    kth.wiljam: INFO