name: kthcloud-ci
"on":
  push:
    branches:
    - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: registry.cloud.cbh.kth.se
        username: ${{ robot$deploy-a78aedc2-6b67-4c2c-95aa-abdd5901e6bb+users }}
        password: ${{ 3XWuo9fUsw2zMbst0rBo1nMRuwJD2Bng }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ registry.cloud.cbh.kth.se/deploy-a78aedc2-6b67-4c2c-95aa-abdd5901e6bb/users }}
