name: kthcloud-ci
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        ref: 'main'
    - name: Print current commit hash
      run: |
        git log -1 --format='%H'
    - name: Debug Output
      run: |
        echo "Current commit SHA: $(git log -1 --format='%H')"
        echo "GitHub Token: $GITHUB_TOKEN"
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: registry.cloud.cbh.kth.se
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKER_TAG }}
